#!/bin/bash
# Quick publish helper — opens files for copy-paste

echo "=== KTG Publish Kit ==="
echo ""
echo "1. LinkedIn"
echo "   cat linkedin.txt | clip"
echo ""
echo "2. Reddit"
echo "   cat reddit.txt | clip"
echo ""
echo "3. X/Twitter (thread — copy each post)"
echo "   cat x-thread.txt"
echo ""
echo "4. Meta/Facebook"
echo "   cat meta.txt | clip"
echo ""
echo "5. Medium"
echo "   Go to medium.com → Write → Import story"
echo "   Or copy from medium.md"
echo ""
echo "6. Buffer"
echo "   Upload buffer.csv to buffer.com"
echo ""
echo "Images needed:"
echo "   - hero-linkedin.png (1200x628)"
echo "   - hero-x.png (1200x600)"
echo "   - hero-square.png (1080x1080)"
echo ""
echo "Review first: review-checklist.md"
